config-version: 3 #DONT CHANGE THIS!
auto-update: true
update-channel: master
lobby:
  x: 0
  y: 0
  z: 0
  world: world
arenas:
  0:
    name: chicken
    team-selection: false
    clear-inventory: true
    countdown: 30
    chicken-health: 50
    player-lives: 3
    players:
      min: 2
      max: 10
    locations:
      world: world
      spawns:
        lobby:
          x: 0
          y: 0
          z: 0
        attacking:
          x: 0
          y: 0
          z: 0
        defending:
          x: 0
          y: 0
          z: 0
        chicken:
          x: 10
          y: 10
          z: 10
      corner1:
        x: 0
        y: 0
        z: 0
      corner2:
        x: 0
        y: 0
        z: 0
      sign:
        x: 0
        y: 0
        z: 0
        world: world
        enabled: false

kits:
  demo:
    name: Demo Kit 1
    items:
      0:
        type: DIAMOND_SWORD
        name: Cute Sword
        amount: 1
        enchantments:
          - FIRE_ASPECT-1
      1:
        type: WOODEN_SWORD
        name: Weak Sword
        amount: 1
        enchantments: [ ]
  demo2:
    name: Demo Kit 2
    items:
      0:
        type: DIAMOND_AXE
        name: Cute Axe
        amount: 1
        enchantments:
          - FIRE_ASPECT-1